# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reunionsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='M', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouse',
        ),
        migrations.AddField(
            model_name='marriage',
            name='spouse_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_a', to='reunionsite.Person'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='spouse_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_b', to='reunionsite.Person'),
        ),
    ]
